const initialState = {
  tags: [
    { name: 'JavaScript', count: 1000 },
    { name: 'React', count: 800 },
    { name: 'Node.js', count: 700 },
    { name: 'HTML', count: 600 },
    { name: 'CSS', count: 500 },
    { name: 'Python', count: 400 },
    { name: 'Java', count: 350 },
    { name: 'Angular', count: 300 },
    { name: 'TypeScript', count: 280 },
    { name: 'Vue.js', count: 250 },
    { name: 'Express.js', count: 200 },
    { name: 'MongoDB', count: 180 },
    { name: 'SQL', count: 150 },
    { name: 'Redux', count: 130 },
    { name: 'GraphQL', count: 120 },
    { name: 'Django', count: 110 },
    { name: 'Flask', count: 100 },
    { name: 'Spring Boot', count: 90 },
    { name: 'C#', count: 80 },
    { name: 'ASP.NET', count: 70 },
    { name: 'PHP', count: 60 },
    { name: 'Laravel', count: 50 },
    { name: 'Ruby', count: 40 },
    { name: 'Rails', count: 35 },
    { name: 'Swift', count: 30 },
    { name: 'Kotlin', count: 25 },
    { name: 'Android', count: 20 },
    { name: 'iOS', count: 15 },
    { name: 'Flutter', count: 10 },
    { name: 'Unity', count: 5 },
  ],
};

export default initialState;